language: php
php:
  - 5.3
  - 5.4

branches:
  only:
    - master
    - develop

env:
  - SYMFONY_VERSION=v2.0.16
  - SYMFONY_VERSION=origin/master


before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
  - gem install compass
